### ISSUE TITLE
Compilation issues on Windows / MSVC

### ISSUE THREAD

**Issue by mathijs727** [Phyronnaz/HashDAG#3]
Hi there,

I'm running into some compilation issues on Windows (Visual Studio 2019):
```
1>hash_table.cpp
1>C:\Users\mathi\Documents\GitHub\HashDAG\src\dags\hash_dag\hash_table.cpp(22,5): error C2653: 'Memory': is not a class or namespace name
1>C:\Users\mathi\Documents\GitHub\HashDAG\src\dags\hash_dag\hash_table.cpp(22,20): error C2062: type 'int' unexpected
1>C:\Users\mathi\Documents\GitHub\HashDAG\src\dags\hash_dag\hash_table.cpp(22,38): error C2653: 'EMemoryType': is not a class or namespace name
1>C:\Users\mathi\Documents\GitHub\HashDAG\src\dags\hash_dag\hash_table.cpp(24,23): error C2653: 'Memory': is not a class or namespace name
1>C:\Users\mathi\Documents\GitHub\HashDAG\src\dags\hash_dag\hash_table.cpp(24,38): error C2275: 'uint32': illegal use of this type as an expression
1>C:\Users\mathi\Documents\GitHub\HashDAG\src\typedefs.h(668): message : see declaration of 'uint32'
...
```

The memory file `memory.h` is included at the top of `hash_table.cpp` but it is not picking up the `Memory` class declared inside.
The cause of the issue is that the compiler is that Microsoft also ships a `memory.h` file in their UCRT library:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/memset-wmemset?view=msvc-160

This can be verified by using the go-to-definition tool in Visual Studio.
By default it will jump to the projects `memory.h` which unfortunately is not what the compiler does (IntelliSense is using a different back-end that is not based on MSVC).
When I change the name of `memory.h` to something else, using go-to-definition will indeed take me to `memory.h` in the UCRT library.

My suggested change is to rename `memory.h` to something that is less likely to clash with system header files.

Best regards,
Mathijs

**Comment by billeter** [comment]
> My suggested change is to rename memory.h to something that is less likely to clash with system header files.

Better fix would be to use the appropriate relative path ("../../memory.h"), as the file is (correctly) included with quotation marks and not <>. Ultimately, one could then avoid adding all the local source directories as include paths, which IMO isn't exactly good practice anyway.

**Comment by mathijs727** [comment]
> ... as the file is (correctly) included with quotation marks and not <>.

Unfortunately the MSVC compiler doesn't seem to differentiate between regular includes & system includes (<>).

> Better fix would be to use the appropriate relative path ("../../memory.h")

This would still break for files that are in the same directory as `memory.h` (or is `#include "./memory.h"` allowed?). Another safe solution could be to move all source code into an uniquely named folder inside src (e.g. `src/HashDag/...`). That way the includes can never clash with system files.
```c++
#include "HashDAG/memory.h"
```

**Comment by billeter** [comment]
> Unfortunately the MSVC compiler doesn't seem to differentiate between regular includes & system includes (<>).

MSVC does differentiate between the two styles of includes. Like any of the "big" C++ compilers, the search order for paths is affected:
 - The quoted form searches files in the same directory first, and checks /I paths only later
 - The bracket form searches /I paths first (and it never searches the local directory, unless that directory is specifically listed with /I)

See https://docs.microsoft.com/en-us/cpp/preprocessor/hash-include-directive-c-cpp?view=msvc-160 for details.

**Comment by mathijs727** [comment]
I had another look at the *.sln/*.proj file and I think there is a very simple reason why this isn't working.
The `src` directory is not added to the include files so the compiler cannot find `memory.h` when it's included from a different directory (e.g. `src/dags/hash_dag/hash_table.cpp`.
